name: Black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10']

    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable